const Constants = {
  USER_INFO: 'user_info',
  ACCESS_TOKEN: 'access_token',
  REFRESH_TOKEN: 'refresh_token',
  REMEMBER_ME_TOKEN: 'remember_me_token',
  USER_ID: 'user_id',
  USER_PARENT: 'user_parent',
  USER_FIRST_NAME: 'first_name',
  USER_LAST_NAME: 'last_name',
  USER_MOBILE_NUMBER: 'mobile',
  USER_PHOTO_PATH: 'photo_path',
  TEAM_ID: 'team_id',
  TEAM_MEMBER_COUNT: 'team_member_count',
  CLUB_ID_FROM_DEEP_LINK: 'club_id_from_deep_link',
  CLUB_NAME_FROM_DEEP_LINK: 'club_name_from_deep_link',
  HEADER_KEY: 'Authorization',
  HEADER_PARTIAL_VALUE: 'Bearer',
  STATUS_SUCCESS: 'success',
  STATUS_ERROR: 'error',
  CONTENT_TYPE: 'application/json',
  // eslint-disable-next-line no-dupe-keys
  REMEMBER_ME_TOKEN: 'rememberMeToken',
  REMEMBER_ME: 'rememberMe',
  STATUS_OK: 200,
  STATUS_FAILED: 400,
  STATUS_TOKEN_EXPIRED: 401,
  STATUS_NO_CONTENT: 204,
  DASHBOARD_SCREEN: 'Dashboard',
  EVENT_SCREEN: 'Event',
  MESSAGE_SCREEN: 'Message',
  NEWS_SCREEN: 'NewsLetter',
  TEAM_SCREEN: 'Team',
  TASK_SCREEN: 'Task',
  EMAIL_INBOX: 1,
  EMAIL_STARRED: 2,
  EMAIL_SENT_MAIL: 3,
  EMAIL_DRAFTS: 4,
  EMAIL_BIN: 5,
  EVENT_GOING_STATUS_ID: 1,
  EVENT_NOT_GOING_STATUS_ID: 2,
  ORDER_BY_NAME_ASC: 'name%20asc',
  BANNER_IMAGE: '',
  ROLE_ADMIN: '1',
  ROLE_MEMBER: '2',
  MAX_LIMIT: 10,
  INITIAL_OFFSET: 0,
  PLATFORM_ADMIN: 45917437, //Stage: 45917437, Live: 25883070
  PLATFORM_ADMIN_NZ: 94797609, //Stage: 94797609, Live: 45917437
  BP_WEB_LINK: 'bpWebLink',
  CLUB_WEB_LINK: 'clubWebLink',
  OTHER_WEB_LINK: 'otherLink',
  FIXTURES_WEB_LINK: 'fixturesLink',
  CONNECTION_OK: 1,
  CONNECTION_DISCONNECTED: 0,
  INTERNET_DISCONNECTED: 2,
  NO_INTERNET_CONNECTION_CODE: 10001,
  NO_INTERNET_CONNECTION: 'No internet connection',
  INVALID_EMAIL_PASSWORD: 'Invalid email or password',
  SELECTED_COUNTRY_CODE: 'selected_country_code',
  SELECTED_COUNTRY_NAME: 'selected_country_name',
  FCM_TOKEN: 'fcm_token',
  DEEP_LINK_RAW_URL: 'deep_link_raw_url',
  TOKEN_SENT_ALREADY: 'token_sent_already',
  CLUB_NOTIFICATION_ID: 2,
  ASSOCIATION_NOTIFICATION_ID: 15,
  ROLE_TYPE: 'role_type',
  ROLE_TYPE_NAME: 'role_type_name',
  ROLE_TYPE_ADMIN: '1',
  ROLE_TYPE_MEMBER: '2',
  ROLE_TYPE_SUPPORTER: '3',
  ROLE_TYPE_PLATFORM_ADMIN: '4',
  ROLE_TYPE_ASSOCIATION_ADMIN: '5',
  ROLE_TYPE_GROUP_MODERATOR: '6',
  MAPBOX_ACCESS_TOKEN:
    'pk.eyJ1IjoiY2x1YmVlei1tYXBib3giLCJhIjoiY2pxcWhyNThkMDBpczN5cXBvaGR6djljZCJ9.XpmHjtVFkodvSzs4rJRpqg',
  TERMS_AND_CONDITIONS_URL: 'https://clubeez.com/terms-and-conditions/',
  PRIVACY_POLICY_URL: 'https://clubeez.com/privacy-policy/',
  // BP Shop
  BP_SHOP_CLIENT_SECRET: '65@#$!er4A32&$sdfr',
  GOOGLE_PLACES_API_KEY: 'AIzaSyBPHEgsgT8pWAxWuqI4qUgj3ifBda_lWmU',
};

export default Constants;
