
export const Fonts = {
    Axiforma: "Axiforma",
    AxiformaLight: "Axiforma-Light",
    AxiformaRegular: "Axiforma-Regular",
    AxiformaMedium: "Axiforma-Medium",
    AxiformaBook: "Axiforma-Book",
    AxiformaBold: "Axiforma-Bold",
    RobotoBlack: 'Roboto-Black',
    RobotoBold: 'Roboto-Bold',
    RobotoLight: 'Roboto-Light',
    RobotoMedium: 'Roboto-Medium',
    RobotoRegular: 'Roboto-Regular',
    RobotoThin: 'Roboto-Thin',
    RobotoBlackItalic: 'Roboto-BlackItalic',
    RobotoBoldItalic: 'Roboto-BoldItalic',
    RobotoItalic: 'Roboto-Italic',
    PoppinsBlack: 'Poppins-Black',
    PoppinsBlackItalic: 'Poppins-BlackItalic',
    PoppinsBold: 'Poppins-Bold',
    PoppinsBoldItalic: 'Poppins-BoldItalic',
    PoppinsExtraBold: 'Poppins-ExtraBold',
    PoppinsExtraBoldItalic: 'Poppins-ExtraBoldItalic',
    PoppinsExtraLight: 'Poppins-ExtraLight',
    PoppinsExtraLightItalic: 'Poppins-ExtraLightItalic',
    PoppinsItalic: 'Poppins-Italic',
    PoppinsLight: 'Poppins-Light',
    PoppinsLightItalic: 'Poppins-LightItalic',
    PoppinsMedium: 'Poppins-Medium',
    PoppinsMediumItalic: 'Poppins-MediumItalic',
    PoppinsRegular: 'Poppins-Regular',
    PoppinsSemiBold: 'Poppins-SemiBold',
    PoppinsSemiBoldItalic: 'Poppins-SemiBoldItalic',
    PoppinsThin: 'Poppins-Thin',
    PoppinsThinItalic: 'Poppins-ThinItalic'
}